# Bind r key to reload conf
unbind r
bind r source-file ~/.tmux.conf

# Bind Asterisk for Synchronizing panes
bind * setw synchronize-panes

# Re-bind Leader to Ctrl+Space
set -g prefix C-Space

# Allow Mouse for resizing
set -g mouse on

# Override starting Index to 1 (default 0)
set -g base-index 1
setw -g pane-base-index 1

# Close the gap in window numbering when a window is killed
set -g renumber-windows on

# Change default scrollback of 2000 lines
set -g history-limit 50000

# Add support for 256-color
set -g default-terminal "tmux-256color"
set -g terminal-overrides ",*256col*:RGB"
set -g terminal-overrides ",xterm-256color:RGB"

set -sg escape-time 10
set -g focus-events on

# Enforce vim navigations
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# Intuitive Split keys that open in the CURRENT dir
unbind %
bind | split-window -h -c "#{pane_current_path}"
unbind '"'
bind - split-window -v -c "#{pane_current_path}"

# Plugins
set -g @plugin "tmux-plugins/tpm"
set -g @plugin "egel/tmux-gruvbox"
set -g @plugin 'MunifTanjim/tmux-mode-indicator'

# Plugin Configs
# Gruvbox
set -g @tmux-gruvbox "dark256"
set -g @tmux-gruvbox-right-status-x '󰃭 %d/%m/%y'
set -g @tmux-gruvbox-right-status-y '󱑌 %I:%M'
set -g @tmux-gruvbox-right-status-z '󰉋 #{b:pane_current_path} #{tmux_mode_indicator}'
set -g @tmux-gruvbox-statusbar-alpha 'true'

# TMUX Mode Indicator
set -g @mode_indicator_prefix_prompt ' P '
set -g @mode_indicator_copy_prompt ' C '
set -g @mode_indicator_sync_prompt ' S '
set -g @mode_indicator_empty_prompt ' N '

# Initialize TMUX Package Manager (tpm)
run "~/.tmux/plugins/tpm/tpm"
